//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_DigitalPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class abbonamento
    {
        public System.DateTime dataAcquisto { get; set; }
        public int cliente_idCliente { get; set; }
        public int tipologia_abbonamento_idTipologia_abbonamento { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual tipologia_abbonamento tipologia_abbonamento { get; set; }

        public override string ToString()
        {
            return this.tipologia_abbonamento.ToString() + "\nAcquistato il " + this.dataAcquisto.Date;
        }
    }
}
