//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_DigitalPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class foto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public foto()
        {
            this.albums = new HashSet<album>();
            this.venditas = new HashSet<vendita>();
            this.progettoes = new HashSet<progetto>();
        }
    
        public int idFoto { get; set; }
        public string nome { get; set; }
        public string tipologia_foto { get; set; }
        public string dimensione { get; set; }
        public string risoluzione { get; set; }
        public int descrizione_idDescrizione { get; set; }
        public int categoria_idCategoria { get; set; }
        public int fotografo_idFotografo { get; set; }
        public Nullable<int> raccolta_temporanea_idRaccoltaTemporanea { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual descrizione descrizione { get; set; }
        public virtual fotografo fotografo { get; set; }
        public virtual raccolta_temporanea raccolta_temporanea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<album> albums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vendita> venditas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<progetto> progettoes { get; set; }

        public override string ToString()
        {
            return "ID Foto (" + this.idFoto + ") - Nome Foto: " + this.nome;
        }
    }
}
