//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_DigitalPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class galleria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public galleria()
        {
            this.mostras = new HashSet<mostra>();
        }
    
        public int idGalleria { get; set; }
        public string nome { get; set; }
        public string luogo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mostra> mostras { get; set; }

        public override string ToString()
        {
            return "ID Galleria (" + this.idGalleria + ") - Nome e Luogo Galleria: " + this.nome + this.luogo;
        }
    }
}
