//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_DigitalPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class intervista
    {
        public int idIntervista { get; set; }
        public string intervista1 { get; set; }
        public int progetto_idProgetto { get; set; }
        public int fotografo_idFotografo { get; set; }
    
        public virtual fotografo fotografo { get; set; }
        public virtual progetto progetto { get; set; }

        public override string ToString()
        {
            return "ID Intervista (" + this.idIntervista + ")";
        }
    }
}
