//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_DigitalPhoto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class digitalphotoEntities : DbContext
    {
        public digitalphotoEntities()
            : base("name=digitalphotoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abbonamento> abbonamentoes { get; set; }
        public virtual DbSet<album> albums { get; set; }
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<descrizione> descriziones { get; set; }
        public virtual DbSet<foto> fotoes { get; set; }
        public virtual DbSet<fotografo> fotografoes { get; set; }
        public virtual DbSet<galleria> gallerias { get; set; }
        public virtual DbSet<intervista> intervistas { get; set; }
        public virtual DbSet<mostra> mostras { get; set; }
        public virtual DbSet<progetto> progettoes { get; set; }
        public virtual DbSet<raccolta_temporanea> raccolta_temporanea { get; set; }
        public virtual DbSet<tipologia_abbonamento> tipologia_abbonamento { get; set; }
        public virtual DbSet<vendita> venditas { get; set; }
    }
}
