//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_DigitalPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class mostra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mostra()
        {
            this.gallerias = new HashSet<galleria>();
        }
    
        public int idMostra { get; set; }
        public string nome { get; set; }
        public System.DateTime data { get; set; }
        public int progetto_idProgetto { get; set; }
    
        public virtual progetto progetto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<galleria> gallerias { get; set; }

        public override string ToString()
        {
            return "ID Mostra (" + this.idMostra + ") - Nome: " + this.nome + " Svolta in Data: " + this.data;
        }
    }
}
