//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_DigitalPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class raccolta_temporanea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public raccolta_temporanea()
        {
            this.fotoes = new HashSet<foto>();
        }
    
        public int idRaccoltaTemporanea { get; set; }
        public string nome { get; set; }
        public System.DateTime data_inizio { get; set; }
        public System.DateTime data_fine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<foto> fotoes { get; set; }

        public override string ToString()
        {
            return "Contenuta in Raccolta T. " + this.nome;
        }
    }
}
