//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_DigitalPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipologia_abbonamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipologia_abbonamento()
        {
            this.abbonamentoes = new HashSet<abbonamento>();
        }
    
        public int idTipologia_abbonamento { get; set; }
        public double prezzo { get; set; }
        public int durata { get; set; }
        public string tipologia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<abbonamento> abbonamentoes { get; set; }

        public override string ToString()
        {
            return "Tipologia Abbonamento: " + this.tipologia + "\nPrezzo: " + this.prezzo + "\nDurata Giorni: " + this.durata;
        }
    }
}
