//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_DigitalPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vendita()
        {
            this.fotoes = new HashSet<foto>();
            this.albums = new HashSet<album>();
        }
    
        public int idVendita { get; set; }
        public System.DateTime data_vendita { get; set; }
        public int cliente_idCliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<foto> fotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<album> albums { get; set; }

        public override string ToString()
        {
            return "Acquisto Effettuato il " + this.data_vendita + ". - Quantità Foto:" + this.fotoes.Count + " Album:" + this.albums.Count;
        }
    }
}
